### ISSUE TITLE
Trying to create two Connectors sequentially  : getting ConcurrentConfigModificationException

### ISSUE THREAD

**Issue by ashikaumanga** [SourceLabOrg/kafka-connect-client#36]
In a SpringBoot app ,we try to create couple of connectors sequentially. Client throws following exception:
Is there a way to fix this ?

`Caused by: org.sourcelab.kafka.connect.apiclient.rest.exceptions.ConcurrentConfigModificationException: Cannot complete request momentarily due to stale configuration (typically caused by a concurrent config change)
	at org.sourcelab.kafka.connect.apiclient.rest.exceptions.InvalidRequestException.factory(InvalidRequestException.java:72)
	at org.sourcelab.kafka.connect.apiclient.KafkaConnectClient.submitRequest(KafkaConnectClient.java:310)
	at org.sourcelab.kafka.connect.apiclient.KafkaConnectClient.getConnector(KafkaConnectClient.java:120)
	at com.company.xxxx.dataplatform.pipeline.client.KafkaConnectApiClient.getConnector(KafkaConnectApiClient.java:60)`

we use Kafka 0.11 and a related bug is fixed in 0.10 : https://issues.apache.org/jira/browse/KAFKA-3673

**Comment by Crim** [comment]
Yea, unfortunately that's just how the kafka-connect service works :/  When you deploy or modify a connector, it is a stop the world action for kafka-connect.  All running connectors are stopped, and then restarted as part of it's rebalance process.  During this period the service refuses to accept additional changes until it has completed returning a concurrent modification error.

2.3.0+ **might** make this less painful as it adds `Kafka Connect now supports incremental cooperative rebalancing.` [KAFKA-8473](https://issues.apache.org/jira/browse/KAFKA-8473) 

I haven't actually tested 2.3.0+ to see if this really makes the issue less pronounced.

**Comment by kennethdowd** [comment]
A retry loop will probably be the best solution OR possibly up upgrading to the latest KC.

https://github.com/SourceLabOrg/kafka-connect-client/issues/36
