### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by ajunwalker** [SourceLabOrg/kafka-connect-client#71]
Hello!

There doesn't seem to be licensing information on this repo. I was wondering if you plan on adding this?

Thank you!

**Comment by Crim** [comment]
Whoops, surprised it went this long unnoticed.  I've added an explicit LICENSE file.  Previously the license could be found here https://github.com/SourceLabOrg/kafka-connect-client/blob/master/build/LICENSE.txt and at the top of every .java file in the repository.

Thanks!
