### ISSUE TITLE
Wrong javadoc for deleteConnector method

### ISSUE THREAD

**Issue by 0xERR0R** [SourceLabOrg/kafka-connect-client#76]
Javadoc was copy-pasted from resumeConnector, 

see https://github.com/SourceLabOrg/kafka-connect-client/blob/master/src/main/java/org/sourcelab/kafka/connect/apiclient/KafkaConnectClient.java#L287

**Comment by Crim** [comment]
Thanks for the heads up.  I'll include a patch to fix this in the next release.
