### ISSUE TITLE
KafkaConnectClient not supporting stop operation

### ISSUE THREAD

**Issue by elene** [SourceLabOrg/kafka-connect-client#86]
Hi,

KafkaConnectClient doesn't implement stop endpoint from [KafkaConnect API](https://docs.confluent.io/platform/current/connect/references/restapi.html#put--connectors-(string-name)-stop). Is it intentional or it just was not implemented? 

It should be straightforward to implement:
- Create a new `PutConnectorStop` class (similar to [this](https://github.com/SourceLabOrg/kafka-connect-client/blob/e5d5888952efd0b4579d9295e5caa260495f7fc7/src/main/java/org/sourcelab/kafka/connect/apiclient/request/put/PutConnectorPause.java)) class and update the endpoint to use stop instead of pause
- Add a new `stopConnector` (similar to [this](https://github.com/SourceLabOrg/kafka-connect-client/blob/e5d5888952efd0b4579d9295e5caa260495f7fc7/src/main/java/org/sourcelab/kafka/connect/apiclient/KafkaConnectClient.java#L283)) and use `PutConnectorStop` class to create a request.
- Add tests

**Comment by Crim** [comment]
I beleive it was just not implemented.  I'd be happy to accept a PR for implementing it, and cut a new release including it. :)

**Comment by anleib** [comment]
The stop operation was recently added in [here](https://github.com/apache/kafka/pull/13424) 
It would be pretty easy to add it here; I'll try to find some time to work on a PR.
Unless you would like to do the PR @elene

**Comment by m8719-github** [comment]
[PR](https://github.com/SourceLabOrg/kafka-connect-client/pull/89) ready for review

**Comment by Crim** [comment]
Thanks for the PR!  I'll try to cut a release here shortly.

**Comment by Crim** [comment]
published 4.0.5 to maven central and cut a release here in github.

Thanks again!
